name: supportpilot

services:
  api:
    build:
      context: .
      dockerfile: dockerfile

    image: supportpilot-api:cpu

    pull_policy: build

    ports:
      - "8001:8000"

    restart: unless-stopped

    init: true

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    stop_grace_period: 20s